### PR TITLE
Release/3.6.2

### PR DESCRIPTION
**Pull request by wzieba**
---

- [ ] I have considered if this change warrants release notes and have added them to the appropriate section in the `CHANGELOG.md` if necessary.

### CODE REVIEW

**Review by AliSoftware — APPROVED** [review]
I'm all good with doing another release, but wanted to ask first: given the small glitches we missed here and there with the sarif helper, did you test the latest fix in a client project before release, by making that project point to `a8c-ci-toolkit#trunk` (or `a8c-ci-toolkit#{commitsha}`) then create test branches and PRs to validate it works? That way we can find potential other issues before doing a new release instead of having to do a 3.6.3 in case we find out we missed another silly thing in 3.6.2 🙃

**Comment by wzieba** [comment]
Usually, I do this, but the thing to test here is about uploading a sarif fail on a _main_ branch. So I'd have to merge `a8c-ci-toolkit#trunk` to main branch of a project, which is something I wanted to omit :/ .

**Comment by AliSoftware** [comment]
> So I'd have to merge a8c-ci-toolkit#trunk to main branch of a project, which is something I wanted to omit :/ .

Ah, got it! Makes sense 👍

**Comment by wzieba** [comment]
On the second thought, let's test this because I'm quite weary of releasing the toolkit 😅

**Comment by wzieba** [comment]
Worked as expected 🎉 https://github.com/Automattic/pocket-casts-android/security/code-scanning

**Pull request merged**
